### ISSUE TITLE
Assert the rules about time_base in HACKING file

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#219]
During my tests today, I had a situation in which `stream.time_base` and `codec_context.time_base` where not the same while decoding!

It was during adapting @markreidvfx's coder tests to my CodecContext.

**Comment by jlaine** [comment]
Isn't this fixed in the latest code?

**Comment by mikeboers** [comment]
The specific issue discussed here is, but I'm still not 100% on time in a few circumstances. I think that the document speaks for itself about being fuzzy, so I guess until it is proven wrong there isn't much point in this being here anymore.
