### ISSUE TITLE
Memory leak while reading frames from preloaded video buffer

### ISSUE THREAD

**Issue by igor-kondratiev** [mikeboers/PyAV#317]
This leak can easily be reproduced with this script
```python
import io

import av


ITERATIONS = 1000
INPUT_SAMPLE_PATH = "/path/to/any/mp4"


def main():
    with open(INPUT_SAMPLE_PATH, "rb") as f:
        input_data = f.read()

    for i in range(ITERATIONS):
        print(f"Iteration {i + 1} started")

        buffer = io.BytesIO(input_data)
        container = av.open(buffer)

        frame = next(container.decode(video=0))

    input("Press enter to exit...")


if __name__ == '__main__':
    main()
```

Increasing number of iterations will cause memory usage constant rising.
I'm using version 0.3.3 but 0.4.0 is affected as well. 
Python version: 3.6.5

I've made some investigations and found actual leaking place. The problem is `ContainerProxy::__dealloc__` method. In case of python file-like buffer there will be two extra objects allocated - `self.iocontext` and `self.buffer` (spoiler: they are both leaking). Next code - `self.ptr.pb = self.iocontext` will force ffmpeg to set `AVFMT_FLAG_CUSTOM_IO` (this happens [here](https://github.com/FFmpeg/FFmpeg/blob/7b8daa771cbdafa6775e476c65afa659cc1afaac/libavformat/utils.c#L558)). Another important thing is that `avformat_close_input` will not free buffer and iocontext if `AVFMT_FLAG_CUSTOM_IO` flag is set - [avformat_close_input code](https://github.com/FFmpeg/FFmpeg/blob/7b8daa771cbdafa6775e476c65afa659cc1afaac/libavformat/utils.c#L4433). As a result, both `self.iocontext` and `self.iocontext.buffer` will not be deallocated.

You could also use [valgrind](http://valgrind.org/) with provided script to verify described behavior. Important note is that valgrind will not point to the buffer that is being allocated in `ContainerProxy::__init__`. `libAV` can reallocate provided buffer for some reasons, so valgrind will show only the last reallocation call-stack.

I've made a fix for version 0.3.3 (here is [link to commit](https://github.com/igor-kondratiev/PyAV/commit/32578ce1354749c9898acb1e8e6be8ef8063e057)) but there is no release branch for this version and I can't create a PR. Are there any chances to release a patch for version 0.3.3?

The code in `ContainerProxy::__dealloc__` was changed in current develop version, but it will not be difficult to adapt this fix for current version. Do you have any plans about dates for the next PyAV release where this fix could be included?

Thank you in advance!

**Comment by mikeboers** [comment]
Thanks for being so thorough!

I don't have dates. I'm hoping I can spend a day on PyAV in the next week or two if work at my primary clients' works out.

**Comment by e-soroush** [comment]
@igor-kondratiev I have used your branch, but the problem remained. I still have memory leakage.

**Comment by jlaine** [comment]
@igor-kondratiev Could you please give #317 a spin? In my tests it eliminated the memory leak identified by valgrind. Thanks for describing the issue in so much detail!

**Comment by jlaine** [comment]
@e-soroush garbage collection is a different topic, and not a bug : it's just about *when* the memory is reclaimed. If you do `del container`, the destructor should be immediately called and you'll reclaim your memory.

**Comment by RomainSabathe** [comment]
Hey, thanks everyone for the input and the fix. Similar to @e3oroush, I'm still having leaks, or so I think. Based on @igor-kondratiev 's example, here's how to reproduce:

`import io

import av


ITERATIONS = 1000
INPUT_SAMPLE_PATH = "/path/to/any/mp4"


def main():
    with open(INPUT_SAMPLE_PATH, "rb") as f:
        input_data = f.read()

    for i in range(ITERATIONS):
        print(f"Iteration {i + 1} started")

        buffer = io.BytesIO(input_data)
        container = av.open(buffer)
        
        frames = [frame for frame in container.decode(video=0)]
        # Optional; just to show that it doesn't solve the issue
        del frames
        del container

    input("Press enter to exit...")


if __name__ == '__main__':
    main()`

Am I doing this right? Thanks!

**Comment by orf** [comment]
For reference, this code does not seem to trigger the issue:

```
import av
import io
import psutil
import gc

us = psutil.Process()

with open('video.mp4', 'rb') as fd:
    content = fd.read()

for i in range(1000):
    gc.collect()
    f = io.BytesIO(content)
    # open video bytestream with PyAv
    video = av.open(f)
    frames = [
        frame
        for packet in video.demux()
        for frame in packet.decode()
    ]
    print(us.memory_percent())

input('done')
```

**Comment by orf** [comment]
I've done some digging into this, it appears to be related to a weird interaction between this library and the garbage collector. Adding a `gc.collect()` after each iteration completely removes the memory leak, even without the `del` statements.

If you have this kind of small loop:
```
for i in range(1000):
    print(f"Iteration {i + 1} started")
    buffer = io.BytesIO(content)
    container = av.open(buffer)
    frames = [frame for packet in container.demux() for frame in packet.decode()]
    gc.collect()
    print(gc.get_stats())
    print(us.memory_percent())
```
You can see something like this in the output:
```
Iteration 18 started
[{'collections': 65, 'collected': 320, 'uncollectable': 0}, {'collections': 2, 'collected': 28, 'uncollectable': 0}, {'collections': 18, 'collected': 25755, 'uncollectable': 0}]
3.2618045806884766
Iteration 19 started
[{'collections': 67, 'collected': 320, 'uncollectable': 0}, {'collections': 2, 'collected': 28, 'uncollectable': 0}, {'collections': 19, 'collected': 27270, 'uncollectable': 0}]
3.2618045806884766
Iteration 20 started
[{'collections': 69, 'collected': 320, 'uncollectable': 0}, {'collections': 2, 'collected': 28, 'uncollectable': 0}, {'collections': 20, 'collected': 28785, 'uncollectable': 0}]
3.261852264404297
```

This is really weird because all of the serious collections seem to come from generation 2 (the last dictionary), removing over a thousand objects an iteration. Generation 2 is supposed to be for the longest lived objects that don't need pruning that often.

So, I'm guessing that:

1. Objects holding on to large memory references are ending up in generation 2 *way, way too fast*
2. This means that they are only freed occasionally.
3. The `__del__` method is not executed, and memory is not freed. So, memory leak!

On top of this the garbage collector has no visibility into the Cython structures, so I guess it has no idea that these seemingly small objects are really large.

I suggest we add an `__enter__` and `__exit__` methods to the `Container`?

```python
with av.open(...) as video:
   ...
```

This would be good anyway I think, because relying on the GC is not fantastic!

**Comment by Mofef** [comment]
I still have a memory leak even with the code given in https://github.com/mikeboers/PyAV/issues/317#issuecomment-430960322
memory consumption is growing quite dramatically. output:
```
1.00917691564
1.58076002958
2.14917120615
2.71771593798
3.28846433156
3.85700906339
4.42555379522
4.9963021888
5.56484692063
6.13339165246
6.70414004604
7.27268477787
7.84343317145
8.41197790328
8.98052263511
9.55127102869
10.1198157605
...
```

So just adding gc.collect() in the loop doesn't seem to solve the issue here.
`av.__version__ == '6.1.2'`

**Comment by Mofef** [comment]
In case it helps:
I ran the loop in `pdb`. exited to a pdb promt via `KeyboardInterupt` and did:
```
ipdb> gc.collect()
19
ipdb> gc.collect()
7
ipdb> gc.collect()
7
ipdb> gc.collect()
7  #umkay...?
ipdb> objgraph.show_most_common_types(limit=20)
function                   10474
tuple                      8543
dict                       8288
list                       3738
_Binding                   3132
weakref                    2218
cell                       1533
builtin_function_or_method 1470
wrapper_descriptor         1424
set                        1179
getset_descriptor          1060
method_descriptor          870
type                       699
WeakSet                    495
property                   479
module                     475
VideoFormatComponent       438
VideoPlane                 435
member_descriptor          373
deque                      362
ipdb> objgraph.by_type('VideoFormatComponent')[222]
<av.video.format.VideoFormatComponent object at 0x7f4712602710>
ipdb> objgraph.show_backrefs([objgraph.by_type('VideoFormatComponent')[222]], max_depth=10)
Graph written to /tmp/objgraph-NXJAAW.dot (114 nodes)
Graph viewer (xdot) not found, generating a png instead
Image generated as /tmp/objgraph-NXJAAW.png
```
Then in a shell I converted `/tmp/objgraph-NXJAAW.dot` to a pdf [objgraph-NXJAAW.pdf](https://github.com/mikeboers/PyAV/files/2910752/objgraph-NXJAAW.pdf), opened it and searched for `"VideoFormatComponent"`. 
I'm honestly way out of my comfort zone, but from what understand circles are a bad thing here. I marked two of them, but there are a couple more. 
![circles_highlighted](https://user-images.githubusercontent.com/1809396/53499125-0851b500-3aa8-11e9-878e-f652052b5c3d.png)

**Comment by Mofef** [comment]
@mikeboers not sure if a comment in a closed issue is enough to get your attention... :)

**Comment by keko950** [comment]
This is a real problem. Would be nice if someone do something with it.

**Comment by mikeboers** [comment]
I'm going to re-open this, mainly because of @Mofef's efforts. I reserve the right to close it and/or make a new one.

@keko950, your comment is not helpful. I'd appreciate if you would be constructive instead of complaining.

**Comment by keko950** [comment]
> I'd appreciate if you would be constructive instead of passive-aggressive complaining.

Didnt mean to be disrespectful with you or anybody! Just tried to get someone's attention at this bug, because it is happening and the only current solution is call to the garbage collector manually, sorry!

**Comment by victorhcm** [comment]
At a first glance, it seems `gc.collect()` did help in my case, capturing a streaming from a single 4K camera. @mikeboers do you have any plans on how to troubleshoot it? If you have any pointers, we'd be glad to help.

**Comment by mikeboers** [comment]
@victorhcm Not really.

@jlaine went through a heroic effort with Valgrind to remove a ton of "real" memory leaks. Given the behaviours discussed above, it really sounds like it isn't a memory leak as much as the garbage collector not collecting.

This feels similar to the origins of the `ContainerProxy`, and now #496 to remove it. There are reference cycles that are not trivial to break, and it has a hard time with them.

Gotta figure out why the collector isn't identifying things, either at all or until we manually call them. Then either make some changes so that isn't triggered, or start overriding `tp_traverse` and `tp_clear` in order to provide our own intelligence.

Thats a lot to say "not really". 😛

**Comment by jlaine** [comment]
Back to the original problem description: I believe the root cause was the absence of a `close()` method on input containers. There is now a close method on containers, and I see much lower memory usage if I do:

```python

import io

import av


ITERATIONS = 1000
INPUT_SAMPLE_PATH = "/path/to/any/mp4"


def main():
    with open(INPUT_SAMPLE_PATH, "rb") as f:
        input_data = f.read()

    for i in range(ITERATIONS):
        print(f"Iteration {i + 1} started")

        container = av.open(io.BytesIO(input_data))
        frame = next(container.decode(video=0))
        container.close()

    input("Press enter to exit...")

if __name__ == '__main__':
    main()
```

To make things even easier I have submitted https://github.com/mikeboers/PyAV/pull/515 which will allow you do do:

```
with av.open(io.BytesIO(input_data)) as container:
    frame = next(container.decode(video=0))
```

**Comment by jlaine** [comment]
I am going to close this issue as I believe the original problem is solved with the introduction of `InputContainer.close()`.

Let's continue the discussion on making frame objects more gc-friendly in https://github.com/mikeboers/PyAV/issues/517

**Comment by hatcherfang** [comment]
@jlaine the memory leak is still exists even the latest version 8.0.3
this is my code monitor by memory_profiler as below:
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     6  56.8711 MiB  56.8711 MiB           1   @profile(precision=4)
     7                                         def test():
     8  56.9922 MiB   0.1211 MiB           1       path = "test.mp4"
     9  64.8047 MiB   7.8125 MiB           1       container = av.open(path)
    10                                             # help(container)
    11                                             # total_frames = container.streams.video[0]
    12                                             # help(total_frames)
    13                                             #path_to_video是你视频的路径
    14  64.8047 MiB   0.0000 MiB           1       first_video = container.decode(video=0)
    15  67.1406 MiB   2.3359 MiB           1       frame = next(first_video)
    16  78.2227 MiB  11.0820 MiB           1       frame_image = frame.to_image()
    17  78.8672 MiB   0.6445 MiB           1       frame_image.save('frame-0.jpg')
    18  78.9258 MiB   0.0586 MiB           1       container.close()
    19  71.2969 MiB  -7.6289 MiB           1       frame_image.close()
    20  71.2969 MiB   0.0000 MiB           1       first_video.close()
    21  71.2969 MiB   0.0000 MiB           1       del frame
    22  71.2969 MiB   0.0000 MiB           1       del frame_image
    23  71.3672 MiB   0.0703 MiB           1       help(container)
    24  71.3672 MiB   0.0000 MiB           1       del container
    25  71.3672 MiB   0.0000 MiB           1       print(gc.collect())
```
You can see that the memory is 56.8711MiB at first,  but the memory increase to 71.3672 MiB at the end.

**Comment by igorshevach** [comment]
@jlaine with all the respect to you container.close() cannot be used when pyAV is used with realtime streaming which can run arbitrarily long  sessions. I am using containers to do various things such as parsing data chunks, decoding and encoding (i.e. resampling audio).
I don't see how container.close() will help me in this situation
